# Generated by Django 4.2.18 on 2025-01-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_id', models.IntegerField(blank=True, null=True)),
                ('card_number', models.CharField(max_length=20, unique=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('last_checkin', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
