# Generated by Django 4.2.18 on 2025-01-30 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_options_employee_unique_contest_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('employee_name',), 'verbose_name': 'Сотрудника', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
